### PR TITLE
Basic Specs

### PR DESCRIPTION
**Pull request by fsbatista**
Implemented the clocks view and most of the checklist view. I'll reach out throught upwork so we can share some ideas.

### CODE REVIEW

**Comment by fsbatista** [comment]
Fixed the bugs we discussed. Only thing pending is the sorting. I need the due date to be on iso format. Currently it just shows a string (e.g. 12:00pm). If you want it to be only relative to the current time of the day, I can do it. Otherwise, we need to improve the due date field. (This also affects the red highlight feature when the task is overdue.)

**Comment by sodapopinsky** [comment]
ok getting close.. 2 things that I see:
- the "tasks completed" count is not calculating correctly
- The due date should be floated all the way to the right with about 15px margin, regardless of screen size.  So If there is no par number, it should be 15px from the right of the screen, if there is a par number, 15px from the grey box with the par number.

For the date, those times don't have a date component, they are always going to be relative to the current day.  So yeah you should be able to create a moment from the string and use that, if that's what you had in mind.

Thanks!

**Comment by fsbatista** [comment]
Ok. I did not have the time to audit the js that calculates the the number of tasks for a given day. What do you think is the best option to get it? (I know you have a method for remaining). As for the other things, I’ll work on it.

**Comment by fsbatista** [comment]
It should be all done now. Except for the remaining tasks number (it's already set up, all you have to do is input the right variable there.)

**Comment by sodapopinsky** [comment]
Thanks felipe, I've been busy but will take a look today and if all is well
will release the funds

**Pull request merged**
